# Generated by Django 3.2.20 on 2023-09-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='CPdepartment',
            new_name='Address1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CPdesignation',
            new_name='Address2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CPemail',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CPmobile',
            new_name='Lname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CPphone',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CPsalutation',
            new_name='pan_no',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='CPskype',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Lastname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bAddress1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bAddress2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bcity',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sAddress1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sAddress2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='scity',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='scountry',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sfax',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sphone1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sstate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='szipcode',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerEmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
