# Generated by Django 3.2.20 on 2023-09-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_loan_loanattach_loancomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_item',
            name='desc',
        ),
        migrations.AddField(
            model_name='invoice_item',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
