# Generated by Django 3.2.20 on 2023-09-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_auto_20230922_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='adjustment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
