# Generated by Django 3.2.20 on 2023-09-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_auto_20230923_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_account',
        ),
    ]
