# Generated by Django 3.2.20 on 2023-09-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0012_remove_expense_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='hsn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
