# Generated by Django 3.2.20 on 2023-09-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0013_expense_hsn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='customeremail',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='gst_treatment',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='sac',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='vendormail',
        ),
    ]
