# Generated by Django 3.2.20 on 2023-09-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0014_auto_20230925_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer'),
        ),
        migrations.AddField(
            model_name='expense',
            name='customeremail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='gst_treatment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='sac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendormail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
