# Generated by Django 3.2.20 on 2023-09-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0018_auto_20230926_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_details',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='gst_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='pan_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
